### ISSUE TITLE
GrainFmt: Grain formatter moving my comments to an odd place

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#1381]
the formatter is moving my comments below this list for some reason which is really wierd behavour, the first image is before formatting and the second is after.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40705786/181652937-71f89331-707a-4c4d-8002-f122a5667369.png">
after formatting vvv
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40705786/181652961-1b17839e-2b42-49fb-b3d7-4e582972fba6.png">

**Comment by marcusroberts** [comment]
I've dug into this, and it's because the lists are parsed with a dummy location in the AST (because the [ ]. is really syntactic sugar for creating a list with the ... operator.    Without a location, the formatter can't work out if the comments come before or after the line.  So it goes for after.

I'll speak with @ospencer about this, we've seen it before but assigning a location to the list is hard.

You'll see the problem go away if the statements are anything but lists
