### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by carcinocron** [grain-lang/grain#1398]
I noticed there was a strong absence of examples, links to examples, etc. Can I have a working example of this but written in grain?

```
console.log `Width: #{window.inner_width}`
console.log `Height: #{window.inner_height}`

let canvas = document.create_element("canvas")
document.body.append_child(canvas)
let ctx = canvas.get_context("2d")
ctx.font = "30px Arial"
ctx.fill_text("Hello World!", 10, 30)

canvas.addEventListener "onmouseover", (event: MouseEvent) {
  console.log(event)
})
```

Also IMO this page https://grain-lang.org/docs/stdlib/dom being empty is worse than having a warning about incoming breaks to backwards compatibility to the API at the top.

**Comment by ospencer** [comment]
That page mentions issue #126 which you can follow for updates on the DOM stdlib. There's no API that's going to break because there's no API (which is why there are no examples). Grain will have support for DOM again but not any time soon.

If you're looking for general examples of Grain programs, check out the Grain guide or the #look-what-i-built channel on Discord.
