### ISSUE TITLE
Will function overloading be supported?

### ISSUE THREAD

**Issue by kee-oth** [grain-lang/grain#1437]
Hi!

I'm just curious if Grain is planning on supporting function overloading?

The main reason I'm interested in overloading is for creating functions that can act as "data-first" when given all the params and also act as "data-last" when not given the data to operate on. This is useful for a number of things but is particularly nice when piping. If `List.map` was overloaded as described (and we had a `pipe` function defined somewhere), we could do:

```js
let myList = [1, 2, 3]

let result1 = List.map((x) => x*2, myList) // [2, 4, 6]

// or
let result2 = pipe(
  myList,
  List.map((x) => x*2),
) // [2, 4, 6]
```

I'm not sure of the difficulties this makes for the type system however.

----------------------------------------

Also, as an unrelated thing, I'm interested in participating in Grain's Discord server but I don't want to give my phone number to Discord. Is there a way to verify without having to give up my phone number? 

I also don't use Twitter or similar social media sites and Grain doesn't have any official email channel so I'm very cut off from the community right now (I think GitHub Issues are the only way for me to communicate at the moment).

Thanks!

**Comment by ospencer** [comment]
Hey @kee-oth, sorry for the late response here (but glad you made it on to the Discord)!

We likely won't support function overloading, since like you mentioned, it's not really possible with Grain's type system. We do however hope to experiment with ways to curry or reorder arguments. There was some discussion here: #401 and #402.

Going to close this for now, but please feel free to reach out either here or on Discord if you have more questions!
