### ISSUE TITLE
Question: How do I create native modules / bindings?

### ISSUE THREAD

**Issue by saenai255** [grain-lang/grain#1439]
I recently learned about Grain, and it looks really cool.

I would like to add more functionality, mostly just to play around, by exposing custom runtime functions. For example, creating a custom Wasm runtime, in a language like Rust, that exposes a `http` library and is available for Grain to use.

My question would be: How do I create these bindings for Grain?

**Comment by marcusroberts** [comment]
I think you're asking about two things.   

I don't think you want to create a custom wasm runtime, as that's a lot of work.  So you'd be looking at using something like wasmtime.

Because of the sandboxing of wasm executables, doing things like making HTTP requests isn't available by default.  You need to interact with the host using WASI.    Here's wasmtime's guide to expanding the functions available through WASI to executables

https://docs.wasmtime.dev/api/wasmtime/

Linking different languages together is I believe difficult at the moment because of a lack of a common memory management / garbage collection standard, but that's coming soon to the wasm standard and then can be supported by languages like Grain.
