### ISSUE TITLE
Bug: `<=` and `>=` do not return the correct result when used with `nan`

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#1459]
![image](https://user-images.githubusercontent.com/40705786/197620188-c63ba539-39d6-4b1f-9a30-b8495a2fb763.png)
As can be seen in the imagine above `<=` and `>=` are returning true when comparing agaist `nan` when they should be returning `false`, `<` and `>` are unaffected.

**Comment by ospencer** [comment]
The problem lies in [cmpFloat](https://github.com/grain-lang/grain/commit/ebd87e4308a8950fd95f060ebc446833b064237c), where when total ordering is not applied, `NaN` is considered equivalent to all other numbers (hence the `<=` check returning true).

For these examples, the result should always be `false`.
