### ISSUE TITLE
Syntax: Add `_` for unused pattern matches

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#1902]
I think we should make the syntax
```
match (x) {
  Err(e) => fail e,
  Ok(_) => _
}
``` 
valid, while you could use `void`. I think `_` better represents that we are just trying to make sure our match is exhaustive and it mirrors the syntax on the other side of the match statemnet for an unused path.

**Comment by alex-snezhko** [comment]
I'm not a huge fan of this syntax; it almost looks like you're trying to return the `_` you defined in the `Ok(_)` pattern. Especially since this syntax would only work in this narrow case of a `match` expression with a void type I think it'd be better to just require `void` as it's immediately clear what's going on

**Comment by phated** [comment]
We're not going to use `_` to represent "unit", we use `void`.
