### ISSUE TITLE
Lang: Revisiting Box

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#202]
Inspired by writing our Map stdlib and [this twitter thread](https://twitter.com/BlaineBublitz/status/1281317794064166912) I was thinking that it might be nice to just have a `mut` keyword instead of using the Box construct.

Thoughts?

**Comment by ospencer** [comment]
I've actually thought about this quite a bit. I actually imagined this as `let mutable` but that might be a little verbose. I'm fully on board with this idea. I think it makes a ton of sense for Grain with its "functional yet flexible" mentality.

We could theoretically get rid of boxes since exported mutable globals seem to be on by default now in WebAssembly.

This change though is largely a matter of the technical stuff, and making sure our typechecking will all still be sound. I believe it would be, but we'd have to make sure. We'd also need to be careful with some of our optimizations, but that could be worked out.

I'd be down to prototype this and see how we feel about it.

**Comment by s0kil** [comment]
Grain is getting Rusty with the `let mut`, haha

**Comment by phated** [comment]
This was completed in #225 🎉
