### ISSUE TITLE
Scope `gensym` in `compcore.re`

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#2175]
Currently when we are compile code to wasm in `compcore.re` we use `gensym` to get a unique name for things like blocks. As `gensym` relies on a global counter a small change to how we generate one block or the introduction of a little bit of code will renumber many things throughout your file, we only really need to validate that things are unique in relation to the current scope, be it a function or the global module we should carry a seperate counter for this scope which will reduce the number of output changes in your generated wasm (Nice for comparing diffs), and more importantly will better support parallel compilation workflows as we are not depending on a single counter.

**Comment by ospencer** [comment]
I personally don't think this is worth the trouble. The global counter guarantees that we get unique names across the whole program (which is a requirement for Binaryen), so making it not global makes it harder to guarantee that property. If you're deving on codegen and it's really hard to diff, then you can just hardcode some names to do comparisons.

**Comment by spotandjake** [comment]
I marked it as low priority because I don't think it is worth the hassle right now to go through factoring it but in the future especially if we want to start looking into making compcore multithreaded it will be a blocker.

**Comment by ospencer** [comment]
To clarify, I mean that I don't think we should do this. Whoever implemented it would need to show that it was correct, and then we'd need to maintain it. I don't think it's worth it for codegen diffs.

To the point about Binaryen scopes, I don't 100% remember where you're allowed to reuse names, which also means that whoever is working on codegen would then also need to understand those semantics to make sure `gensym` works, which defeats the entire purpose of `gensym`.

As for multithreading, that's not something we'd tackle before whole Grain (unless Grain got multithreading before then) so that's quite a ways off. Even then, codegen probably just gets functorized or we just have multiple copies of the compiler running as separate wasm instances, and in either case, we wouldn't need to change `gensym`.

**Comment by spotandjake** [comment]
Closing this as after the discussion above it's clear it's not something we want to change.
