### ISSUE TITLE
Lang: Floats

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#255]
This has come up a few time, we need to support floats in the language. This requires compiler support and an additional stdlib to work with floats.

@ospencer I know you have a ton of knowledge, thoughts and details on how this would be implemented. Can you outline that in this issue?

**Comment by ospencer** [comment]
Yup, this should be implemented as two new types: `Float32` and `Float64`. Implementation will directly follow `Int32` and `Int64`: https://github.com/grain-lang/grain/blob/master/compiler/src/typed/builtin_types.re#L140. 

Only one open question: 

Syntax for `Float32` and `Float64` literals (`1.`, `1.5`, etc. are reserved for the `Number` type). `Int32` and `Int64` use `42l` and `42L` respectively, so `1.5f` and `1.5F` would be nice, but that might be confusing as other languages use `f` for 32 bits and `d` for 64 bits, and capitalization is ignored. I feel that if this is documented well, it won't really matter. I'd vote for `f` and `F`.

When someone is ready to pick this up, feel free to chat with me and I can walk you through the Int32/64 code.

**Comment by phated** [comment]
@ospencer Since the literals will be reserved for the number type, I actually propose the following:
* Rename `Int32` (which doesn't seem to exist in the stdlib?) as `Int` and `Int64` as `BigInt`, which mirrors the the lowercase `l` and the uppercase `L`
* Then name the floats as `Float` and `BigFloat`, with `f` and `F` as the syntax.

This keeps everything consistent, and gives hints to someone's mind from the usage ("I imported `bigfloat`, so I need to use a big F").

What do you think?

**Comment by ospencer** [comment]
It's not a bad idea, but the name `BigInt` nearly always refers to arbitrary precision integers (which will be the default with our new number system). I think that `32` and `64` are important to designate how many bits you're working with.

I wouldn't worry all too much about the number suffixes. It should be pretty rare that someone is actually creating fixed-precision numbers _and_ is writing a bunch of literals in their code. I also feel like no one ever remembers that languages support this anyway, and people usually just do `Int32.of_int 5` instead of writing `5l` anyway.
