### ISSUE TITLE
Browser APIs

### ISSUE THREAD

**Issue by LightningK0ala** [grain-lang/grain#27]
Are there plans to support browser APIs?

**Comment by ospencer** [comment]
The short answer is yes.

The longer answer is that it'll really take some time for all of them to get implemented. We're trying to make it easy to write these bindings (since they'll pretty much all be calling out to JavaScript until WebAssembly supports them) so anyone could help get them implemented.

We do have some rudimentary DOM support, which currently needs to be fixed (see #30). We'll probably start with the most widely used APIs, like expanding the DOM API before we move onto things like the devices API, etc.

It'll be quite the journey, but we'll get there! 🎢

**Comment by LightningK0ala** [comment]
🚀 Alright! ✌️😁
