### ISSUE TITLE
Refactor Frontmatter in compcore.re

### ISSUE THREAD

**Issue by belph** [grain-lang/grain#278]
As we push off more and more runtime functionality to our WASM stdlib, the first section of compcore.re keeps growing. I think we should try to refactor some of this (maybe just the imports) into a separate file.

**Comment by ospencer** [comment]
@belph this appears to be a duplicate of #85. 

I actually pretty much got all of this done, but held off on the PR because of the GC work. Though now with that + the switch to Reason, that branch is maybe a lost cause. You can see what the idea was here: https://github.com/grain-lang/grain/compare/clean-up-compcore

Either way, we should probably close this in favor of #85.

**Comment by belph** [comment]
Ah, okay, I missed that. Yeah, I think we should probably start over that work now that we're on Reason, but I think that branch is a good inspiration for what we should do.

**Closing this issue as invalid.**
