### ISSUE TITLE
Better Overflow Messages

### ISSUE THREAD

**Issue by peblair** [grain-lang/grain#301]
When adding our new number system in, the values we pass to our overflow exception were a bit of a rush job. These should ideally be improved, whether that be with more specific variants of `GRAIN_ERR_OVERFLOW` (e.g. `GRAIN_ERR_OVERFLOW_PLUS`) or just more consistency about what the user sees. Currently, we essentially just pick one of the numbers and display it to the user (which isn't super informative).

@grain-lang/core We can discuss what we'd like the messages to look like here.

**Comment by z0w0** [comment]
I was looking at tackling this as a first issue. Would it make sense to keep it throwing a `GRAIN_ERR_OVERFLOW` but then having another constant that it throws with a more specific reason (`GRAIN_ERR_OVERFLOW_PLUS` etc.) instead of the existing number it gives? Or would it be better to just have one error constant for each type of overflow?

**Comment by ospencer** [comment]
IMO, we can just throw `GRAIN_ERR_OVERFLOW` and not display any numbers. If we wanted to be really cool, we could display both numbers and the operation, which could potentially save a debugging step. I was initially against that because I didn't want to add a ton more errors, but I suppose only addition and multiplication can overflow.

That said, we might not be _quite_ ready to start on this since we haven't decided on what we're doing (sorry for mislabeling this as ready!). We're having our Grain community meeting tomorrow, so I'll bring it up then 🙏
