### ISSUE TITLE
Check Overflow Safety of Numeric Operations

### ISSUE THREAD

**Issue by peblair** [grain-lang/grain#304]
With the introduction of the new number system, there are a couple of loose ends which need to be checked for overflow-safety:

- In `numberPlusMinusSimpleHelp`, we coerce the simple int (`x ∈ (-1 << 30, 1 << 30)`) into a `f32` and add it to the already-f32 RHS. This could probably overflow. What is the best way to make it more hardened?
- In `numberPlusMinusRationalHelp` and `numberTimesDivideRationalHelp`, our `(Rational, Rational)` operations work by performing the grade-school algorithm of multiplying together the appropriate numerators and denominators and then simplifying to a reduced fraction. This is guarded against overflows, but I'm sure there is a smarter way to do these operations which will permit a larger domain of fractions to be usable with these functions.
- In `numberTimesDivideInt64Help`, we perform `(Int64, Float32)` multiplication/division by coercing the `i64` into a `f32` and doing the operation. This should be safe, but I want to make someone else think about it too before declaring it as such.

**Comment by indolering** [comment]
I believe the state-of-the-art in this area is [As If Infinitely Ranged](https://ieeexplore.ieee.org/abstract/document/5635126/).  IIRC, it adds a 5-10% performance overhead.  My apologies if this is unhelpful.

**Comment by ospencer** [comment]
The cases in the first and third bullet points are never hit because an invariant of the number system is that floats of type `Number` are always f64s (and we should probably enforce this invariant in the code, but that's a separate issue). Converting a `Float32` to a `Number` always promotes to an f64, float literals are f64s, and operations involving f64s always produce f64s. That said, the logic you mentioned would overflow into `Infinity`, but that's expected. Which is all to say that we don't need to worry about those bullet points!

As for rationals, we recently made them arbitrary precision which completely solves the overflow problem.

With that, I believe we can close this issue! I'll let it be closed by a PR that cleans up any TODOs in the code.
