### ISSUE TITLE
is let keyword necesary?

### ISSUE THREAD

**Issue by fega** [grain-lang/grain#33]
I would be great to remove it, as I saw in the docs, it doesn't looks neccesary.

**Comment by ospencer** [comment]
It's not technically necessary. 

It's more of a developer familiarity thing, since the people who would want to use Grain are probably pretty familiar with JavaScript or an ML language where `let` is pretty comfortable. 

You could definitely argue that Python doesn't require it and gets along just fine (and it would be even more clear in Grain since reassignments aren't allowed without using a box). 

It's something to consider, for sure.

**Comment by belph** [comment]
Personally, I am a fan of `let`, as it helps visually clarify the scope in which a variable is defined. Moreover, while Grain does not currently have traditional mutation, sticking with the keyword increases the language's syntactic flexibility on that front in the future.

As @ospencer implies, however, a lot of it really boils down to preference. I don't want to totally count out `let`-less Grain, but I'm not totally sure we want to take that route at this moment.

**Comment by wiredearp** [comment]
If Grain does "not currently have traditional mutation", wouldn't `const` be a better keyword until this comes along :question:
