### ISSUE TITLE
Compiler build failing (arch x84_64)

### ISSUE THREAD

**Issue by avery-laird** [grain-lang/grain#335]
Hi there, building the compiler is failing for me:

```
[avery@avery compiler]$ yarn build
yarn run v1.22.5
$ esy install && esy compile && esy copy-compiler
info install 0.6.7 (using esy.json)
info building @opam/dune@opam:2.7.1@70792dee
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/dune@opam:2.7.1
    # esy-build-package: pwd: /home/avery/.esy/3/b/opam__s__dune-opam__c__2.7.1-c45903c6
    # esy-build-package: running: 'env' '-u' 'OCAMLLIB' 'ocaml' 'bootstrap.ml'
    ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot unix.cma boot/libs.ml boot/duneboot.ml
    ./.duneboot.exe
# esy-build-package: running: './dune.exe' 'build' '-p' 'dune' '--profile' 'dune-bootstrap'
       ocamlfind (internal) (exit 2)
    /usr/bin/ocamlfind printconf path > /tmp/dune87b744.output
    ocamlfind: Config file not found - neither /lib/findlib.conf.d/ocaml-secondary-compiler.conf nor the directory /lib/findlib.conf.d/ocaml-secondary-compiler.conf.d
    error: command failed: './dune.exe' 'build' '-p' 'dune' '--profile' 'dune-bootstrap' (exited with 1)
    esy-build-package: exiting with errors above...
    
  building @opam/dune@opam:2.7.1
esy: exiting due to errors above
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm unfamiliar with how esy handles builds, so a bit lost for how to solve the issue. Any help/suggestions would be greatly appreciated

**Comment by ospencer** [comment]
Hey @avery-laird! Honestly, I'm not sure if anyone has ever tried to build on arch. The versions of things all look good, though. It shouldn't make a difference, but is anything different if you run `yarn compiler build` from the root of the project?

**Comment by avery-laird** [comment]
yes, actually I tried that first, with the exact same result. For now, maybe there's a way for me to just use my local dune installation? It seems like esy is building its own?

**Comment by phated** [comment]
Unfortunately not, esy completely sandboxes everything.

**Comment by avery-laird** [comment]
ah ok. Well thanks for the help anyways. If there's nothing obviously jumping out as a common issue, then this probably seems like an esy issue. Maybe I would have some luck following up there

**Comment by ospencer** [comment]
Definitely give that a shot. If you just want to try out the language, we've got a docker image you can try out. If you were looking to contribute, we're currently working through getting a docker-based workflow set up, and we'll probably have something in a few days.

**Comment by avery-laird** [comment]
sounds great, I will check out the docker option if I can't get the build working. I have opened an issue at the esy repo, so hopefully they can offer a solution. Unless there are any objections, I'll keep this issue open in case I hear back from esy and a modification to the build process is required

**Comment by avery-laird** [comment]
I've heard back from esy. They suggested removing `esy.lock`, and that did the trick. I see that `esy.lock` is tracked, but if this file is generated during the build process anyway, then maybe it's worth removing. As I said, esy is not really my area of expertise, so I'm closing this issue and you can decide whether to keep tracking `esy.lock`

**Comment by phated** [comment]
@avery-laird I'm glad that fixed it. I'm going to explain and hypothesize a little bit: We use the `esy.lock` because it generates a source-of-truth for our dependencies. This allows us to export and re-import dependencies across different runs on the same platform, assuming the dependencies list doesn't change. This is emulating the "yarn.lock" workflow but for native development.

The problem with the OCaml ecosystem is that things aren't immutable. Often opam files in the registry will be modified without receiving a version bump. In addition, esy tries to smooth over some problems in the ecosystem using their "opam overrides" concept. This usually lags behind the rest of the ecosystem, so we might have updated our lockfile the pulled in the official opam version and in the meantime, they updated the "opam overrides" to use a different build script. We probably just need to do an update of the lockfile to pull this in. I'll try to look at doing this soon.
