### ISSUE TITLE
Grain produces WebAssembly binaries that wasm2wat can't read

### ISSUE THREAD

**Issue by autodidaddict** [grain-lang/grain#644]
1. Created a `hello.gr` file:
```
print("hello world")
```

2. Build the file

3. Try and use a tool like wasm2wat to get the raw code:
```
wasm2wat hello.gr.wasm -o test.wat
0002c7c: error: unexpected opcode: 0xfc 0xb
```

I'm running Grain v0.3.1 on Ubuntu 20.04, which is the `.deb` file I downloaded this morning as the latest.

**Comment by srenatus** [comment]
+1, with wabt's wasm2wat 1.0.13 and 1.0.23, I see the same that you're reporting.

FWIW `wasp wasm2wat` produces this:

```
<unknown>:00002c7a: Unknown opcode: 252
    2002 2003 fc0b 0041 feff ffff 06
              ^^                    
<unknown>:00002c84: Expected final end instruction
    ffff 060b 1200 2001 2002 2003 
                                  
<unknown>:00002c8c: Unknown opcode: 252
    2002 2003 fc0a 0000 41fe ffff ff
              ^^                    
<unknown>:00002c97: Expected final end instruction

....
```

**Comment by ospencer** [comment]
You'll need to pass `--enable-bulk-memory` for `wasm2wat` to produce a `.wat` file, since it's not on by default yet. We don't have it behind a flag because it's marked as a [completed WebAssembly proposal](https://github.com/WebAssembly/proposals/blob/master/finished-proposals.md). We might change our minds on that, but most of the runtimes already support it.

Also, Grain v0.4 will have a `--wat` flag to produce the `.wat` file automatically 🎉 https://github.com/grain-lang/grain/pull/620

Hope that helps! Going to close this since it's not an issue with the generated wasm files. Let us know if you run into any other tooling issues 🙂
