### ISSUE TITLE
Error referencing variables in record construction without a trailing comma

### ISSUE THREAD

**Issue by cician** [grain-lang/grain#679]
I encountered a compilation error for something I intuitively think would be correct syntax. I can't simply assign an existing variable in a record constructor, yet I can pass constants or function calls with closures referencing same variables. Then I managed to make it work by randomly appending a trailing comma after the entry.

``` grain
import List from "list"
import Map from "map"
import Option from "option"

record MyRecord<k, v> {
	entries: String
}

let s = "hello"

let a = {
import List from "list"
import Map from "map"
import Option from "option"

record MyRecord {
	entry: String
}

let s = "hello"

let a = {
	// this doesn't work
	entry: s

	// ...yet this does!
	//entry: s,

	// as well as this
	//entry: "hello"

	// or this:
	//entry: Option.unwrap(Option.map((id) => s, Some("ignore me")))
}

print(a)
```

**Comment by ospencer** [comment]
@cician Thanks for the report. This is happening because the compiler isn't sure if you're creating a record with field `entry`, or if you have a block that returns the single value `entry` which is annotated as an "any" type. Of course, it should be the record here.

The other variations you tried work because they can't be parsed as a block! One of the downsides of parsers that handle ambiguous grammars.

**Comment by cician** [comment]
I understand now.

Personally I'd rather prefer more strict and verbose syntax if that could help prevent such issues.
